jetbrains_toolbox_version: "1.26.5.13419"
state_storage_dir: /.ansible-state-tracking
font:
  name: UbuntuMono
  version: v2.2.2

op_connect_user: opconnect

remote_pets_path: "~{{ ansible_user }}/.config/home-pets"
dotfiles_path: "{{ remote_pets_path }}/dotfiles"

linker_path: "{{ remote_pets_path }}/playbooks/files/linker.sh"
nginx_config_helper_path: "{{ remote_pets_path }}/playbooks/files/nginx-config-helper.sh"
