################
# Logging
log-async
# log-queries
log-dhcp

#################
# DNS
# Send DNS queries to dnscrypt-proxy
no-resolv
server=127.0.0.1#5353

domain-needed
bogus-priv
local-ttl=30
domain=home.moreharts.com,10.0.0.0/16,local

# Explicity DNS entries, outside DHCP created ones
host-record=dns.home.moreharts.com,{{ network.ip }},0     # Self
host-record=router.home.moreharts.com,10.0.0.1,60         # Router
cname=home.moreharts.com,dmz.home.moreharts.com,60
cname=ha.moreharts.com,dmz.home.moreharts.com,60
cname=dns.moreharts.com,dmz.home.moreharts.com,60
cname=vpn.moreharts.com,dns.home.moreharts.com,60


################
# DHCP
dhcp-authoritative
dhcp-range=10.0.0.50,10.0.127.254,255.255.128.0,12h
dhcp-option=option:router,10.0.0.1
dhcp-leasefile=/var/lib/misc/dnsmasq.leases

# Static assignments
dhcp-host=laptop-server,{{ network.ip }} # Self, although I don't think this works. Just have to have a static IP
dhcp-host=dmz,10.0.0.6
dhcp-host=vm-host,10.0.0.5
dhcp-host=development,10.0.0.21
dhcp-host=3c:6a:2c:1b:e9:9c,bondbridge,10.0.0.11
dhcp-host=d0:bf:9c:36:dc:5e,lp1,10.0.0.12
dhcp-host=52:54:00:54:38:5d,homeassistant,10.0.95.242
dhcp-host=plex,10.0.0.10

# Include all files in a directory which end in .conf
conf-dir=/etc/dnsmasq.d/,*.conf

# If a DHCP client claims that its name is "wpad", ignore that.
# This fixes a security hole. see CERT Vulnerability VU#598349
dhcp-name-match=set:wpad-ignore,wpad
dhcp-ignore-names=tag:wpad-ignore
