[Interface]
#Address = 10.0.128.1/17
Address = 10.0.200.1/24
ListenPort = 51820
PrivateKey = WL7/4szhzuQufT1taMp5igKEBBzuH6HIm8GDLS+MMVI=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o enxa0cec8d7d026 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o enxa0cec8d7d026 -j MASQUERADE
