- name: DNS/DHCP Server
  hosts: dns
  tasks:
  - ansible.builtin.include_tasks: './tasks/allow-wireguard.yaml'
  - name: Allow HTTPS access for 1password bridge
    become: yes
    community.general.ufw:
      rule: limit
      port: ssh
      proto: tcp
  - name: Allow server ports
    become: yes
    community.general.ufw:
      rule: allow
      port: "{{ item.port }}"
      src: "{{ item.src | default(network_netmask) }}"
      proto: "{{ item.proto }}"
    with_items:
      - port: 80
        proto: tcp
        src: any
      - port: 443
        proto: tcp
        src: any

  - name: Adding server packages
    become: yes
    ansible.builtin.apt:
      name: "{{ item }}"
    with_items:
      - dotnet
      - nginx-core

  # Install nginx and config files
  - import_tasks: './nginx-with-letsencrypt.yaml'

  - name: Add 1password Conect user
    become: yes
    ansible.builtin.user:
      name: "{{ op_connect_user }}"
      home: "/home/{{ op_connect_user }}/"
      password: '*'
      password_lock: true
      system: true
      groups: docker

  - name: Copy 1Password Connect files
    become: yes
    ansible.builtin.copy:
      src: ../dotfiles/system/op-connect/
      dest: "/home/{{ op_connect_user }}"
      owner: "{{ op_connect_user }}"
      group: "{{ op_connect_user }}"

  - name: Link 1Password Connect systemd unit file
  - name: Link concentrator Wireguard config
    become: yes
    ansible.builtin.template:
      src: "../dotfiles/system/op-connect/opconnect.service"
      dest: "/lib/systemd/system/opconnect.service"
    register: wireguard_configs_updated

  - name: Reload (possibly) affected system services
    become: yes
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: yes
      state: restarted
    with_items:
      - opconnect

