- name: DMZ externally-accessible server
  hosts: dmz
  tasks:
  - ansible.builtin.include_tasks: './tasks/allow-wireguard.yaml'
  
  - name: Allow rate-limited SSH from outside the local network
    become: yes
    community.general.ufw:
      rule: limit
      port: ssh
      proto: tcp

  # Install nginx and config files
  - import_tasks: './nginx-with-letsencrypt.yaml'
