- name: DNS/DHCP Server
  hosts: dns
  tasks:
  - ansible.builtin.include_tasks: './tasks/allow-wireguard.yaml'

  - name: Allow rate-limited SSH from outside the local network
    tags:
      - firewall
    become: yes
    community.general.ufw:
      rule: limit
      port: ssh
      proto: tcp

  - name: Allow server ports
    tags:
      - firewall
    become: yes
    community.general.ufw:
      rule: allow
      port: "{{ item.port }}"
      src: "{{ item.src | default(network_netmask) }}"
      proto: "{{ item.proto | default('any') }}"
    with_items:
      - port: bootps
      - port: 53
        proto: udp
      - port: 67
        proto: udp
      - port: 68
        proto: udp
      - port: 80
        proto: tcp

  - name: Adding server packages
    become: yes
    ansible.builtin.apt:
      name: "{{ item }}"
    with_items:
      - qrencode
      - dnsmasq
      - dnscrypt-proxy
      - nginx-core

  # TODO porkbun ddns

  # Ensure network matches desired variables
  - name: Updating netplan
    become: yes
    ansible.builtin.template:
      src: "../dotfiles/system/netplan/static-template.yaml"
      dest: /etc/netplan/99-server.yaml
    register: netplan_updated

  - name: Applying netplan
    become: yes
    when: "netplan_updated.changed"
    ansible.builtin.shell: netplan apply

  # Install server config files
  - name: Template out server configuration files
    tags:
      - system-config
      - nginx
      - wireguard
    become: yes
    ansible.builtin.template:
      src: "../dotfiles/system/{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - src: "wireguard-public-endpoint/wg0.conf"
        dest: "/etc/wireguard/wg0.conf"
      - src: "wireguard-public-endpoint/generate-client.sh"
        dest: "/etc/wireguard/generate-client.sh"
      - src: "dnsmasq.conf"
        dest: "/etc/dnsmasq.conf"
      - src: "dnscrypt-proxy/dnscrypt-proxy.toml"
        dest: "/etc/dnscrypt-proxy/dnscrypt-proxy.toml"
      - src: "nginx/sites-available/dns.home.moreharts.com.conf"
        dest: "/etc/nginx/sites-enabled/"
    register: system_configs_updated

  - name: Nginx HTML files
    tags:
      - nginx
    become: yes
    ansible.builtin.template:
      src: "../dotfiles/system/{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - src: "nginx/www-roots/dns.home.moreharts.com/index.html"
        dest: "/var/www/html/"
    register: system_configs_updated

  - name: Initial config for Wireguard concentrator 
    tags:
      - wireguard
    become: yes
    ansible.builtin.shell:
      chdir: /etc/wireguard
      creates: server.key
      cmd: |
        wg genkey | sudo tee "server.key" | wg pubkey | sudo tee "server.key.pub"

  - name: Reload (possibly) affected system services
    when: "system_configs_updated.changed"
    become: yes
    tags:
      - services
      - nginx
      - wireguard
    ansible.builtin.systemd:
      name: "{{ item }}"
      enabled: yes
      state: restarted
    with_items:
      - dnsmasq
      - dnscrypt-proxy
      - wg-quick@wg0
      - nginx

