- name: Allow server ports
  tags:
    - nginx
  become: yes
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    src: "{{ item.src | default(network_netmask) }}"
    proto: "{{ item.proto }}"
  with_items:
    - port: 80
      proto: tcp
      src: any
    - port: 443
      proto: tcp
      src: any

- name: Adding nginx
  tags:
    - nginx
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - nginx-core
    - python3-certbot-nginx

- name: Setup nginx config and certbot
  become: yes
  tags:
    - nginx
  ansible.builtin.command:
    argv:
      - bash
      - "{{ nginx_config_helper_path }}"
      - "{{ item }}"
  with_items: "{{ nginx_hosts }}"
