- name: Allow server ports
  tags:
    - nginx
  become: yes
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    src: "{{ item.src | default(network_netmask) }}"
    proto: "{{ item.proto }}"
  with_items:
    - port: 80
      proto: tcp
      src: any
    - port: 443
      proto: tcp
      src: any

- name: Adding nginx
  tags:
    - nginx
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - nginx-core
    - python3-certbot-nginx

- name: Copy nginx files to host
  tags:
    - nginx
  ansible.builtin.copy:
    src: '../../dotfiles/system/nginx/'
    dest: "/tmp/nginx-ansible-config/"
  register: nginx_config_result

- name: Setup nginx config and certbot
  tags:
    - nginx
  # when: "nginx_config_result.changed"
  become: yes
  ansible.builtin.command:
    argv:
      - bash
      - /tmp/nginx-ansible-config/nginx-config-helper.sh
      - "{{ item }}"
  ignore_errors: false
  with_items: "{{ nginx_hosts }}"
