upstream dns {
    server dns.home.moreharts.com max_fails=1 fail_timeout=2s;
}

# HTTPS redirect
server {
    listen 80;
    server_name dns.moreharts.com;

    server_tokens off;

    location /.well-known {
        alias /var/www/;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# Main config
server {
    listen 443 ssl;
    server_name dns.moreharts.com;

    ssl_certificate_key /etc/letsencrypt/live/dns.moreharts.com/privkey.pem;
    ssl_certificate     /etc/letsencrypt/live/dns.moreharts.com/fullchain.pem;

    server_tokens off;

    location /.well-known {
        alias /var/www/;
    }

    location / {
        proxy_pass http://dns;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
    }
}