upstream homeassistant {
    server homeassistant.home.moreharts.com:8123 max_fails=1 fail_timeout=2s;
}

# HTTPS redirect
server {
    listen 80;
    server_name ha.moreharts.com;

    server_tokens off;

    location /.well-known {
        alias /var/www/;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# Main config
server {
    listen 443 ssl;
    server_name ha.moreharts.com;

    ssl_certificate_key /etc/letsencrypt/live/ha.moreharts.com/privkey.pem;
    ssl_certificate     /etc/letsencrypt/live/ha.moreharts.com/fullchain.pem;

    server_tokens off;

    location /.well-known {
        alias /var/www/;
    }

    location /dns {
        alias /var/lib/misc/dnsmasq.leases;
    }

    location / {
        proxy_pass http://homeassistant;
        proxy_http_version 1.1;
        # proxy_set_header Host $http_host;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}